%{
-About-
This script curates the cell list generated by Oufti. It removes cells that
do not have meshes, adds extra fields to the cell structure (e.g. area
or cell length) and converts area from pixels to micrometer units

-Inputs-
cellList: a cell list generated by Oufti must be open in the workspace in
MATLAB

-varargin-
N/A

-Outputs-
A curated cellList in which the area field is in square micron units

-Example-
Click Run after you opened a cellList in MATLAB
   
-Supplementary-
N/A

-Keywords-
cellList area
-Dependencies-
The following dependencies are part of the Oufti software package:
CL_getFrame.m
CL_removeCell.m
CL_cellId2PositionInFrame.m
getextradata.m
-References-
Paintdakhi A, Parry B, Campos M, Irnov I, Elf J, Surovtsev I, and
Jacobs-Wagner C. (2016). Oufti: an integrated software package for
high-accuracy, high-throughput quantitative microscopy analysis. Molecular
Microbiology. 99(4):767-777.
-Author-
Brad Parry, 2018, July
Molly Scott, 2018, July
Nick Takacs, 2018, July
%}
%**************************************************************************************
%%%    removing cells that do not have meshes  %%%%%%
for ii = 1:length(cellList.meshData)
[~,cellIds] = CL_getFrame(ii,cellList);
if cellIds == 0, continue;end
for jj = cellIds
if ~isfield(cellList.meshData{ii}{CL_cellId2PositionInFrame(jj,ii,cellList)},'mesh')
cellList =  CL_removeCell(jj,ii,cellList);
end
end
end
%**************************************************************************************
%**************************************************************************************
%%%  adding extra fields to cell structures such as area, length, etc %%%%%
for ii = 1:length(cellList.meshData)
for jj = 1:length(cellList.meshData{ii})
cellList.meshData{ii}{jj} = getextradata(cellList.meshData{ii}{jj});
end
end
%**********
%%% converts area from pixel units to micrometer units
cellList = Area_to_microns2(cellList);
%*************