function [cellList] = Add_DnaN_Area(cellList, path_to_images)
%{
-About-
Function to calculate the relative intracellular area of fluorescently
labeled DnaN. The field 'relative_dnaN_area' is added for each cell in the
cellList.

-Inputs-
cellList:  cellList generated by Oufti, loaded into matlab. 
            
path:   full path to folder containing DnaN fluorescence images. This
        folder should contain a separate image for each frame included in
        the cellList
 
-varargin-
NA

-Outputs-
cellList:   updated cellList containing DnaN information, the field
            'relative_dnaN_area' is added for each cell
-Example-
NA

-Supplementary-
NA

-Keywords-
DnaN, Relative DnaN area, cellList, Oufti

-Dependencies-
filterIM (function that performs bandpass Gaussian filtering on an image)
Load_Image_Series (function that loads in a series of individual images and
combines them into a stack)
This function requires functions from Matlab's image processing toolbox:
    graythresh.m
    imcrop.m
    poly2mask.m
    regionprops.m

-References-
NA

-Author-
Sander Govers, 22 October 2018
%}

%% Clean out cell entries in cellList that do not contain correct information

%Initiate counter to keep track of the number of removed cells
counter=0;

%Loop through frames and cells in the cellList
for ii=1:length(cellList.meshData)
    for jj=1:length(cellList.meshData{ii})
        %Remove empty entries, entries that do not contain cell mesh
        %information or very short entries
        if isempty(cellList.meshData{ii}{jj}) ||...
                ~isfield(cellList.meshData{ii}{jj},'mesh') ||...
                length(cellList.meshData{ii}{jj}.mesh)<=4
            cellList.meshData{ii}{jj}=[];
            %Add 1 to counter if cell entry is removed
            counter=counter+1;
        end
    end
end
%Display the total number of cell entries that was removed from the
%cellList
disp(['Number of cell entries cleaned out : ',num2str(counter)]);

%% Extract DnaN information

dnaN_images = Load_Image_Series(path_to_images);

%Display progress bar
w = waitbar(0,'Extracting DnaN information');

%Loop through frames included in the cellList
for ii = 1:length(cellList.meshData)
    %Select corresponding dnaN image
    dnaN_single_image = dnaN_images(:,:,ii); 
    %Run filterIM function to enhance features in fluorescent image
    filtered_image = filterIM(dnaN_single_image,'fq',1,'sl',10,'ithresh',0);
    %Loop through all cells in the frame
    for jj=1:length(cellList.meshData{ii})
        %Only do this for frames containing cells
        if ~isempty(cellList.meshData{ii}{jj})
            %Extract cell mesh and box region
            cell_mesh = cellList.meshData{ii}{jj}.mesh;
            cell_box=cellList.meshData{ii}{jj}.box;
            %Extract coordinates of cell outline
            outline_left = [cell_mesh(:,1);flipud(cell_mesh(:,3))];
            outline_right = [cell_mesh(:,2);flipud(cell_mesh(:,4))];
            %Define region of image to be cropped, corresponding to where
            %the cell is
            crop_region = [cell_box(1),cell_box(2),cell_box(3),cell_box(4)];
            %Crop original image so that only the small region containing the cell
            %remains
            cropped_image = imcrop(dnaN_single_image, crop_region);
            %Crop filtered image so that only the small region containing the cell
            %remains
            filtered_cropped_image = imcrop(filtered_image, crop_region);
            %Normalize intensities in cropped filtered image
            filtered_cropped_image = (filtered_cropped_image-min(filtered_cropped_image(:)))./(max(filtered_cropped_image(:))-min(filtered_cropped_image(:)));
            %Define mask for image corresponding to the cell
            cell_mask = poly2mask(double(outline_left-crop_region(1)+1),double(outline_right-crop_region(2)+1),size(filtered_cropped_image,1),size(filtered_cropped_image,2));
            %Set all pixel values outside of the cell to 0 so they do not
            %interfere with the threshold calculation
            filtered_cropped_image(~cell_mask)=0;
            %Calculate threshold for resulting image
            [threshold,~] = graythresh(filtered_cropped_image(:));
            %Increase threshold size to include more of the DnaN signal
            threshold =1.5*threshold;
            %Initiate return black and white image (where 0 values correspond to undetected
            %signal and 1 to detected signal)
            bw_cropped_image = zeros(size(filtered_cropped_image,1),size(filtered_cropped_image,2));
            %Identify pixels that exceed threshold
            pixels_above_threshold = filtered_cropped_image>=threshold;
            %Set pixel that exceed the threshold to 1
            bw_cropped_image(pixels_above_threshold)=1;
            %Set pixels that fall outside of the cell area to 0
            bw_cropped_image(~cell_mask)=0;   
            %use regionprops function to extract properties of DnaN and
            %the corresponding cell
            dnaN_stats = regionprops(bw_cropped_image,cropped_image,'Area','PixelValues');
            cell_stats = regionprops(cell_mask,cropped_image,'Area','PixelValues');

            cellList.meshData{ii}{jj}.relative_dnaN_area=[];
            %Only calculate the relative DnaN area if the properties for
            %the DnaN signal were extracted
            if ~isempty(dnaN_stats)
                %Due to occassional issues (<0.1 %) with the regionprops function for these images,
                %use try statement to calculate the relative DnaN area and
                %write it into the cellList
                try
                    cellList.meshData{ii}{jj}.relative_dnaN_area=dnaN_stats.Area/cell_stats.Area;
                %If calculation fails, set relative area to NaN
                catch
                    cellList.meshData{ii}{jj}.relative_dnaN_area=NaN;
                end
            end
        end
    end
    waitbar(ii/length(cellList.meshData));
end
close(w);
end
